# This is a sample aws-auth-patch.yml file. 
# Actual aws-auth-patch.yml will be created at /System/Volumes/Data/private/tmp/aws-auth-patch.yml path.

apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::000800101118:role/eksctl-simple-jwt-api-nodegroup-NodeInstanceRole-AKF49LHQM9VN
      username: system:node:{{EC2PrivateDNSName}}
    - system:masters
      rolearn: arn:aws:iam::000800101118:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-06-24T03:30:13Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "2040"
  uid: 11a7f6e3-6819-4940-8b91-d245a332cc4b
